// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cqonxjgmskwzvcswxbrv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNxb254amdtc2t3enZjc3d4YnJ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5OTIyNjQsImV4cCI6MjA2MzU2ODI2NH0.2i1r3jdOZlLXnHDB-c0n4VEeBxWPDocKy84baA9Ka8A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);